name: killercustommessage
main: com.example.Plugin
version: 1.0
api-version: 1.15
commands:
  kcm:
    description: Set a custom message when kill a player
    usage: /kcm set <custom-message>
    aliases: [killcustommessage]
    subcommands:
      set:
        description: Set a custom message when kill a player
        usage: /kcm set <custom-message>
        permission: kcm.command.set
        executor: com.example.commands.KillCustomMessageCommand